set nocompatible              " be iMproved, required

if &shell =~# 'fish$'   "This is a compatibility fix for fish-shell and plugins
    set shell=sh
endif

filetype off                  " required

if empty(glob("~/.vim/bundle/Vundle.vim"))
  call system('git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim')
endif

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Navigation
Plugin 'scrooloose/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'
Plugin 'christoomey/vim-tmux-navigator'


" Search
Plugin 'mileszs/ack.vim'                " Experimenting with ag, the silver searcher
if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif


" colors
Plugin 'altercation/vim-colors-solarized'

" syntax support
Plugin 'keith/tmux.vim'
Plugin 'saltstack/salt-vim'
Plugin 'Glench/Vim-Jinja2-Syntax'
Plugin 'dag/vim-fish'
Plugin 'fatih/vim-go'

" some fancy things are being added here
Plugin 'Shougo/neocomplete.vim'
Plugin 'Shougo/neosnippet'
Plugin 'Shougo/neosnippet-snippets'
Plugin 'Konfekt/FastFold'

" Misc
Plugin 'tpope/vim-fugitive'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" ================ Solarized ================================
if !empty(glob("~/.vim/bundle/vim-colors-solarized"))
  set background=dark
  colorscheme solarized
endif

" ================ File types ================================

set encoding=utf-8
filetype on          " enables filetype detection
filetype plugin on   " enables filetype specific pugins
filetype indent on   " enables filetype detection for indenting
syntax enable


" ================ Lines and cursors  ========================
"
set number                      "Line numbers are good
set backspace=indent,eol,start  "Allow backspace in insert mode
set gcr=a:blinkon0              "Disable cursor blink
" Display tabs and trailing spaces visually
set list listchars=tab:→\ ,trail:∙


" ================ Turn Off Swap Files ==============
"
set noswapfile
set nobackup
set nowritebackup


" ================ Persistent Undo ==================
" " Keep undo history across sessions, by storing in file.
" " Only works all the time.
"
let backupdir = expand('~/.vim/backups')
if !isdirectory(backupdir)
  call mkdir(backupdir)
  endif
  set undodir=~/.vim/backups
  set undofile

" ================ Indentation ======================
"
set autoindent
set smartindent
set smarttab

"I'm a spaces guy
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab

set nowrap
set linebreak " Wrap lines at convenient points

let g:indent_guides_auto_colors = 1
let g:indent_guides_start_level = 2
let g:indent_guides_guide_size  = 1


" ================ Folds ============================
" I like folding
set foldenable        "fold by default
set foldmethod=syntax


" ================ NerdTree autocmd stuffss =============
if !empty(glob("~/.vim/bundle/nerdtree"))
  let g:NERDTreeIndicatorMapCustom = {
      \ "Modified"  : "✹",
      \ "Staged"    : "✚",
      \ "Untracked" : "✭",
      \ "Renamed"   : "➜",
      \ "Unmerged"  : "═",
      \ "Deleted"   : "✖",
      \ "Dirty"     : "✗",
      \ "Clean"     : "✔︎",
      \ "Unknown"   : "?"
      \ }
endif

"================= Remaping =================
" F1 Gbrowse
nnoremap <F1> :Gbrowse<CR>
"F2 line number toggle
nnoremap <F2> :set nonumber!<CR>:set foldcolumn=0<CR>
" <F3> = Toggle NERDTree
nnoremap <F3> :NERDTreeToggle<CR>
" <F4> = Toggle paste mode
set pastetoggle=<F4>

"================= enable powerline ====================
python from powerline.vim import setup as powerline_setup
python powerline_setup()
python del powerline_setup
set laststatus=2

let g:neocomplete#enable_at_startup = 1
