if [ -d ~/.bash_profile.d ]; then
  for i in ~/.bash_profile.d/*
  do
    source ${i}
  done
fi


if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
